#!/bin/sh

# COLORS :
# ~~~~~~~~
Green='\033[0;32m'        # GREEN
Cyan='\033[1;36m'         # CYAN
Yellow='\e[1;33m'         # YELLOW  
No='\e[0m'

# CLEAR Terminal :
# ~~~~~~~~~~~~~~~~
clear

# INSTALLING QT THEME ENGINE PACKAGES :
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo -e "${Cyan}INSTALLING QT PACKEGES...${No}"
echo ""
sudo pacman -Sy --needed qt5-wayland kvantum qt5ct qt6ct qt6-tools qt5-quickcontrols2 qt5-graphicaleffects
echo ""
echo -e "${Green}INSTALLING QT PACKAGES - DONE ${No}"
echo ""
echo ""

# ENVIRONMENT VARIABLES :
# ~~~~~~~~~~~~~~~~~~~~~~~
echo -e "${Cyan}ADDING ENVIRONMENT VARIABLES...${No}"
echo ""
echo -e "QT_QPA_PLATFORMTHEME=qt5ct\nQT_QPA_PLATFORMTHEME=qt6ct\nQT_QPA_PLATFORM=wayland\nQT_WAYLAND_DISABLE_WINDOWDECORATION=1\nQT_AUTO_SCREEN_SCALE_FACTOR=1\nMOZ_ENABLE_WAYLAND=1" | sudo tee -a /etc/environment
echo ""
echo -e "${Green}ADDING ENVIRONMENT VARIABLES - DONE ${No}"
echo ""
echo ""

# REBOOTING :
# ~~~~~~~~~~~
read -rep $'\e[1;33mWOULD YOU LIKE TO REBOOT NOW (Y,N)  \e[0m' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    exec systemctl reboot --no-wall
else
    exit
fi