#!/bin/sh

# COLORS :
# ~~~~~~~~
Green='\033[0;32m'        # GREEN
Cyan='\033[1;36m'         # CYAN
Yellow='\e[1;33m'         # YELLOW  
No='\e[0m'

# CLEAR TERMINAL :
# ~~~~~~~~~~~~~~~~
clear

# INSTALLING MISSING FIRMWARE PACKAGES : 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo -e "${Cyan}INSTALLING MISSING FIRMWARE... ${No}"
echo ""
yay -Sy --needed aic94xx-firmware wd719x-firmware ast-firmware upd72020x-fw
sudo pacman -Sy --needed linux-firmware-qlogic
echo ""
echo -e "${Green}INSTALLING MISSING FIRMWARE - DONE ${No}"
echo ""
echo ""

# SETTING TTY CONSOLE FONT :
# ~~~~~~~~~~~~~~~~~~~~~~~~~~
echo -e "${Cyan}SETTING TTY CONSOLE FONT... ${No}"
echo ""
sudo touch /etc/vconsole.conf
echo -e "KEYMAP=us\nFONT=default8x16\nFONT_MAP=8859-2" | sudo tee -a /etc/vconsole.conf
echo ""
echo -e "${Green}SETTING TTY CONSOLE FONT - DONE ${No}"
echo ""
echo ""

# RE-BUILDING MKINITCPIO - CONSOLE FONT :
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo -e "${Cyan}RE-BUILDING MKINITCPIO... ${No}"
echo ""
sudo sed -i 's/BINARIES=()/BINARIES=(setfont)/g' /etc/mkinitcpio.conf
sudo mkinitcpio -P
echo ""
echo -e "${Green}RE-BUILDING MKINITCPIO - DONE ${No}"
echo ""
echo ""

# REBOOTING :
# ~~~~~~~~~~~
read -rep $'\e[1;33mWOULD YOU LIKE TO REBOOT NOW (Y,N)  \e[0m' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    exec systemctl reboot --no-wall
else
    exit
fi